name: Daily Brief Generation

on:
  schedule:
    # Run at 9:00 AM UTC every day (adjust timezone as needed)
    - cron: "0 9 * * *"
  workflow_dispatch:
    # Allow manual triggering for testing

jobs:
  generate-brief:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Daily Brief
        run: node src/index.js
        env:
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          GOOGLE_PERSONAL_REFRESH_TOKEN: ${{ secrets.GOOGLE_PERSONAL_REFRESH_TOKEN }}
          GOOGLE_WORK_REFRESH_TOKEN: ${{ secrets.GOOGLE_WORK_REFRESH_TOKEN }}
          TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          NODE_ENV: production

      - name: Read Brief Content
        id: brief
        run: |
          # Check if HTML file exists
          if ls output/daily-brief-*.html 1> /dev/null 2>&1; then
            echo "Found HTML file(s):"
            ls -la output/daily-brief-*.html
            
            # Use base64 encoding to preserve HTML content exactly
            BRIEF_CONTENT=$(cat output/daily-brief-*.html | base64 -w 0)
            echo "content_base64=$BRIEF_CONTENT" >> $GITHUB_OUTPUT
            echo "Base64 content length: ${#BRIEF_CONTENT}"
          else
            echo "ERROR: No HTML file found in output directory"
            exit 1
          fi

      - name: Prepare Email Content
        id: prepare
        run: |
          # Decode the base64 content and save to file
          echo "${{ steps.brief.outputs.content_base64 }}" | base64 -d > email_content.html
          
          # Debug: Show first few lines of HTML content
          echo "Debug: First 20 lines of HTML content:"
          head -20 email_content.html
          
          # Add footer to HTML (insert before closing body tag)
          sed -i 's|</body>|<hr style="margin: 20px 0; border: none; border-top: 1px solid #ccc;"><p style="font-size: 12px; color: #666; text-align: center;"><small>Generated on: ${{ github.event.head_commit.timestamp }}<br>Workflow run: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Details</a></small></p></body>|' email_content.html
          
          # Debug: Verify HTML structure after footer addition
          echo "Debug: Last 10 lines after footer addition:"
          tail -10 email_content.html
          
          # Extract date for subject
          TODAY=$(date +"%B %d, %Y")
          echo "email_date=$TODAY" >> $GITHUB_OUTPUT

      - name: Send Daily Brief Email
        uses: dawidd6/action-send-mail@v6
        if: success()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "Daily Brief - ${{ steps.prepare.outputs.email_date }}"
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: Daily Brief Bot <${{ secrets.GMAIL_USERNAME }}>
          html_body: file://email_content.html
          convert_markdown: false

      - name: Upload Brief as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: daily-brief-${{ github.run_number }}
          path: |
            output/
            *.html
          retention-days: 30

      - name: Send Notification on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Daily Brief Generation Failed - ${new Date().toDateString()}`,
              body: `The daily brief generation workflow failed. Please check the logs for details.\n\nWorkflow run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });