name: Daily Brief Generation

on:
  schedule:
    # Run at 9:00 AM UTC every day (adjust timezone as needed)
    - cron: "0 9 * * *"
  workflow_dispatch:
    # Allow manual triggering for testing

jobs:
  generate-brief:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Daily Brief
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Generate today's daily briefing by running the daily brief application.
            
            Instructions:
            1. Run `node src/index.js` to generate the daily brief
            2. If there are any errors, troubleshoot and fix them
            3. Ensure the brief is generated successfully
            4. The brief should include today's calendar events and tasks
            
            The application connects to Google Calendar and Todoist APIs using environment variables.
          claude_args: "--model claude-sonnet-4"
        env:
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          GOOGLE_PERSONAL_REFRESH_TOKEN: ${{ secrets.GOOGLE_PERSONAL_REFRESH_TOKEN }}
          GOOGLE_WORK_REFRESH_TOKEN: ${{ secrets.GOOGLE_WORK_REFRESH_TOKEN }}
          TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
          NODE_ENV: production

      - name: Upload Brief as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: daily-brief-${{ github.run_number }}
          path: |
            output/
            *.md
          retention-days: 30

      - name: Send Notification on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Daily Brief Generation Failed - ${new Date().toDateString()}`,
              body: `The daily brief generation workflow failed. Please check the logs for details.\n\nWorkflow run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });